config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => "homes#about"

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    resource :members, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :cart_items, only: [:index, :create, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm', as: :orders_confirm
    get 'orders/complete' => 'orders#complete', as: :orders_complete
    resources :orders, only: [:index, :new, :create, :show]
  end



  get "admin" => "admin/homes#top"

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    post '/admin/sign_in', to: 'admins/sessions#create', as: :admin_session
    delete '/admin/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    resources :homes, only: []
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :personal]
    get 'orders/:id/personal' => 'orders#personal', as: :orders_personal


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,         presence: true, length: {maximum: 10 }
  validates :first_name,        presence: true, length: {maximum: 10 }
  validates	:last_name_kana,    presence: true, length: {maximum: 10 }
  validates :first_name_kana,   presence: true, length: {maximum: 10 }
  validates :telephone_number, 	presence: true, length: {maximum: 12, minimum: 10 }
  validates :postal_code,       presence: true, length: {maximum: 7 }
  validates :address, 		      presence: true, length: {maximum: 255 }
  validates :email, 			      presence: true, length: {maximum: 255 }
  validates :is_active,        inclusion: [true, false]



  has_many :cart_items
  has_many :orders
  has_many :order_details


  def active_for_authentication?
    super && is_active
  end

  def inactive_message
    is_active ? super : :mail_not_replied
  end
end

app/models/order.rb
class Order < ApplicationRecord
  
  enum payment: {クレジットカード: 0, 銀行振込: 1}
  
  has_many :order_details
  
  belongs_to :customer
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
		@customer = Customer.find(params[:id])
	end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
		@customer = Customer.find(params[:id])
			if @customer.update(customer_params)
			redirect_to admin_customer_path
			flash[:notice_edit] = "会員情報が更新されました!"
		else
			render 'edit'
		end
	end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number,:is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all

  end

  def show
    @order = Order.find(params[:id])
  end

  def personal
    @orders = Order.where(customer_id: params[:id])
    render :index
  end

end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController

  def index
    @carts = current_customer.cart_items.all

  end

  def create
    @cart = CartItem.new(cart_item_params)
    @cart.customer_id = current_customer.id
    @cart.save
    redirect_to cart_items_path
  end

  def update
    @cart = CartItem.find(params[:id])
    @cart.update(cart_item_params)
    redirect_to cart_items_path
  end

  def destroy
    @cart = CartItem.find(params[:id])
    @cart.destroy
    redirect_to cart_items_path
  end

  def destroy_all
    @carts = current_customer.cart_items.all
    @carts.destroy_all
    redirect_to cart_items_path

  end


  private

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  
  def index
    
    @items_all = Item.all
    @items = Item.page(params[:page]).per(8)
  end
  
  def show
    @item = Item.find(params[:id])
    @cart = CartItem.new
  end

end

app/controllers/customer/members_controller.rb
class Customer::MembersController < ApplicationController

  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(member_params)
    redirect_to members_path
  end

  def unsubscribe

  end

  def withdraw
    @customer = current_customer
    @customer.update(is_active: false)
    redirect_to root_path
  end

  private

  def member_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:postal_code,:address,:telephone_number)
  end


end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  def index
    @orders = current_customer.orders.all
    @order_details = current_customer.order_details.all
  end

  def new
    @order = Order.new
    @coustomer = Customer.find_by(id: current_customer.id)
    @carts = current_customer.cart_items.all
  end

  def confirm
    @carts = current_customer.cart_items.all
    @order = Order.new(order_confirm_params)
  end

  def create
    @order = Order.new(order_confirm_params)
    @carts = current_customer.cart_items.all

    if @order.save

      @carts.each do |cart|
        @order_detail = OrderDetail.new
        @order_detail.order_id = @order.id
        @order_detail.item_id = cart.item_id
        @order_detail.purchase_price = tax_include(cart.item.price)
        @order_detail.amount = cart.amount
        @order_detail.save
      end

      @carts.destroy_all
      redirect_to orders_complete_path
    end

  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end






  private

  def order_confirm_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping, :claim, :payment)
  end

  def tax_include(price)
    return (price*1.1).floor
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  private
  def after_sign_up_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  private
  def after_sign_in_path_for(resource)
    root_path
  end
  def after_sign_out_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customer/orders/complete.html.erb
<div class="container">

<div class="row">
    <div class="col-xs-12 thanks-box center-block">
        <h2>ご購入ありがとうございました！</h2>
    </div>
</div>
</div>

app/views/customer/orders/confirm.html.erb
<div class="container main">

  <div class="row">

    <div class="page-title">
      <span>注文情報確認</span>
    </div>

    <div class="order-tables cart-index">

        <div class="order-contents col-xs-8">
           <table>

            <thead>
              <tr>
                <th colspan="2">商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
              </tr>
            </thead>

            <tbody>
              <% @carts.each do |cart| %>
                <tr>
                  <td>
                    <%= attachment_image_tag cart.item, :image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
                  </td>
                  <td><%= cart.item.name %></td>
                  <td><%= tax_include(cart.item.price).to_s(:delimited) %></td>
                  <td><%= cart.amount %></td>
                  <td><%= (tax_include(cart.item.price)*cart.amount).to_s(:delimited) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>

        <div class="billing-info col-xs-3">
          <table class="table table-bordered">
              <tr>
                <th>商品合計</th>
                <td><%= total_price(@carts).to_s(:delimited) %></td>
              </tr>
               <tr>
                  <th>配送料</th>
                  <td><%= @order.shipping %></td>
                </tr>
                <tr>
                  <th>ご請求額</th>
                  <td><%= @order.shipping + total_price(@carts)%></td>
                </tr>
          </table>
        </div>
    </div>

  </div>

  <div class="row">
     <div class="shipping-info col-xs-7">
        <table class="table no-border">
          <tr>
            <td class="info-title">支払方法</td>
            <td><%= @order.payment %></td>
          </tr>
          <tr>
            <td class="info-title">お届け先</td>
            <td><%= "#{@order.postal_code} #{@order.address}"  "\n" " #{@order.name}\n" %></td>
          </tr>

        </table>
    </div>
    </div>
     <div class="row">
    <div class="col-xs-2 col-xs-offset-5">


        <%= form_with model: @order, url: orders_path(@order), local: true do |f| %>
          <%= f.hidden_field :postal_code %>
            <%= f.hidden_field :address %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :payment %>
            <%= f.hidden_field :customer_id, :value => current_customer.id  %>
            <%= f.hidden_field :shipping, :value => 800  %>
            <%= f.hidden_field :claim, :value => (total_price(@carts)+800)  %>
            <%= f.submit "購入を確定する", class:"btn btn-success center-block" %>
<% end %>

    </div>
    </div>
</div>

app/views/customer/orders/index.html.erb
<div class="container main">

    <div class="row">

        <div class="col-xs-12">

            <div class="page-title">
                <span>注文履歴一覧</span>
            </div>

            <table class="table table-bordered">
                <tr>
                    <th>注文日</th>
                    <th>配送先</th>
                    <th>注文商品</th>
                    <th>支払金額</th>
                    <th class="col-xs-1">注文詳細</th>
                </tr>
                <% @orders.each do |order| %>
                <tr>
                    <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
                    <td><%= order.postal_code %><br><%= order.address %></td>
                    <td><% order.order_details.each do |order_detail| %>
                    <%= order_detail.item.name %><br>
                    <% end %>
                    </td>
                    <td><%= order.claim.to_s(:delimited) %></td>
                    <td><%= link_to "表示する", order_path(order.id), class:"btn btn-primary center-block" %></td>
                    
                </tr>
                <% end %>
            </table>

        </div>

    </div>

</div>

app/views/customer/orders/new.html.erb
<div class="container main">

  <div class="row order-info-new">

    <div class="page-title">
      <span>注文情報確認</span>
    </div>

     <%= form_with model: @order, url: orders_confirm_path, local: true do |f| %>
    <div>

        <div class="payment-new col-xs-12">
          <span class="info-title">支払い方法</span><br>

          <div class="payment-method-buttons col-xs-offset-1 col-sm-10">

            <%= f.radio_button :payment, :クレジットカード, checked: true, class:"radio" %>
            <%= f.label :payment, "クレジットカード" %><br>
            <%= f.radio_button :payment, :銀行振込, checked: true, class:"radio" %>
            <%= f.label :payment, "銀行振込" %>
          </div>
        </div>

    </div>

    <div class="shipping-new col-xs-12">
      <span class="info-title">お届け先</span><br>
        <table>

          <tr>
            <td><%= f.label :postal_code, "郵便番号（ハイフンなし）" %></td>
            <td><%= f.text_field :postal_code, value: @coustomer.postal_code %></td>
          </tr>

          <tr>
            <td><%= f.label :address, "住所" %></td>
            <td><%= f.text_field :address, value: @coustomer.address, size:10*7%></td>
          </tr>

          <tr>

            <td><%= f.label :name, "宛名" %></td>
            <td><%= f.text_field :name, value: @coustomer.last_name+@coustomer.first_name %></td>
          </tr>
           <%= f.hidden_field :customer_id, :value => current_customer.id  %>
            <%= f.hidden_field :shipping, :value => 800  %>
            <%= f.hidden_field :claim, :value => (total_price(@carts)+800)  %>
        </table>
        <%= f.submit "確認画面に進む", class: "btn btn-primary center-block link" %>
    </div>

  </div>
  </div>
<% end %>

app/views/customer/orders/show.html.erb
<div class="container main">

  <div class="row">

    <div class="page-title">
      <span>注文履歴詳細</span>
    </div>

    <div class="order&details-info">

      <div class="order-info col-xs-5 ">
        <span class="info-title">注文情報</span>
        <table class="table table-bordered">
          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>配送先</th>
            <td>
              <%= @order.postal_code %><br>
              <%= @order.address %><br>
              <%= @order.name %>
            </td>
          </tr>
          <tr>
            <th>支払方法</th>
            <td><%= @order.payment %></td>
          </tr>
        </table>
      </div>

      <div class="details-info col-xs-3">
        <span class="info-title">請求情報</span>
          <table class="table table-bordered">
            <tr>
              <th>商品合計</th>
              <td><%=total_price_detail(@order.order_details).to_s(:delimited) %></td>
            </tr>
            <tr>
              <th>配送料</th>
              <td><%= @order.shipping %></td>
            </tr>
            <tr>
              <th>ご請求額</th>
              <td><%= @order.claim.to_s(:delimited) %></td>
            </tr>
          </table>
      </div>
    </div>
    </div>

    <div class="row">
      <div class="order-contents col-xs-7">
        <span class="info-title">注文内容</span>
         <table class="table table-bordered">
            <tr>
              <th >商品</th>
              <th>単価（税込)</th>
              <th>個数</th>
              <th>小計</th>
            </tr>
            <% @order.order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.purchase_price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= order_detail.purchase_price * order_detail.amount %></td>
            </tr>
            <% end %>
          </table>

      </div>
    </div>

  </div>

</div>