config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => "homes#about"

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    resource :members, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :cart_items, only: [:index, :create, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm', as: :orders_confirm
    get 'orders/complete' => 'orders#complete', as: :orders_complete
    resources :orders, only: [:index, :new, :create, :show]
  end



  get "admin" => "admin/homes#top"

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    post '/admin/sign_in', to: 'admins/sessions#create', as: :admin_session
    delete '/admin/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    resources :homes, only: []
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :personal]
    get 'orders/:id/personal' => 'orders#personal', as: :orders_personal


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  
  enum payment: {クレジットカード: 0, 銀行振込: 1}
  
  has_many :order_details
  
  belongs_to :customer
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all

  end

  def show
    @order = Order.find(params[:id])
  end

  def personal
    @orders = Order.where(customer_id: params[:id])
    render :index
  end

end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController

  def index
    @orders = current_customer.orders.all
    @order_details = current_customer.order_details.all
  end

  def new
    @order = Order.new
    @coustomer = Customer.find_by(id: current_customer.id)
    @carts = current_customer.cart_items.all
  end

  def confirm
    @carts = current_customer.cart_items.all
    @order = Order.new(order_confirm_params)
  end

  def create
    @order = Order.new(order_confirm_params)
    @carts = current_customer.cart_items.all

    if @order.save

      @carts.each do |cart|
        @order_detail = OrderDetail.new
        @order_detail.order_id = @order.id
        @order_detail.item_id = cart.item_id
        @order_detail.purchase_price = tax_include(cart.item.price)
        @order_detail.amount = cart.amount
        @order_detail.save
      end

      @carts.destroy_all
      redirect_to orders_complete_path
    end

  end

  def show
    @order = Order.find(params[:id])
  end

  def complete
  end






  private

  def order_confirm_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :shipping, :claim, :payment)
  end

  def tax_include(price)
    return (price*1.1).floor
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container main">
  <div class="row">
    <div class="page-title">
    <span>注文履歴一覧</span>
    </div>
    <div class="page-title col-md-8 col-md-offset-2">
   

      <table class="table table-hover">
        <div class="no-norder">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
          </tr>
         <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.strftime('%Y/%m/%d') %>
							<% end %>
            </td>
            <td>
              <%= order.customer.last_name %><%= order.customer.first_name %>
            </td>
            <td>
              <%= total_amount(order.order_details) %>
            </td>
          </tr>
          <% end %>
        </div>
      </table>
    </div>

  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container main">

  <div class="row">

    <div class="head-box">
      <div class = "col-md-8 col-md-offset-1">
        <div class = "headbox page-title">
          <span>注文履歴詳細</span>
        </div>
        <table>
          <tr>
            <th>購入者</th>
            <td>
              <%= link_to admin_customer_path(@order.customer) do %>
              <%= @order.customer.last_name %><%= @order.customer.first_name %>
              <% end %>
            </td>
          </tr>

          <tr>
            <th>配送先</th>
            <td>
              <p>〒<%= @order.postal_code %> <%= @order.address %></p>
              <%= @order.name %>
            </td>
          </tr>

          <tr>
            	<th>支払方法</th>
            	<td><%= @order.payment %></td>
          </tr>

        </table>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="left-box">
      <div class = "col-xs-7 col-md-offset-1">
        <table = width="600">

          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.purchase_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.purchase_price*order_detail.amount %></td>
          </tr>
          <%end%>
        </table>
      </div>
    </div>
    
    <div class="right-box">
      <div class="col-xs-3">
        <table>
          <tr>
            <th>商品合計</th>
            <td><%= total_price_detail(@order.order_details).to_s(:delimited) %>円</td>
          </tr>
          <tr>
            <th>送料</th>
            <td><%= @order.shipping%>円</td>
          </tr>
          <tr>
            <th>請求合計</th>
            <td><%= @order.claim.to_s(:delimited) %>円</td>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>