config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  get 'about' => "homes#about"

  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }

  scope module: :customer do
    resources :items, only: [:index, :show]

    get 'members/unsubscribe' => 'members#unsubscribe'
    patch 'members/withdraw' => 'members#withdraw'

    resource :members, only: [:show, :edit, :update]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all', as: :cart_items_destroy_all
    resources :cart_items, only: [:index, :create, :update, :destroy]

    post 'orders/confirm' => 'orders#confirm', as: :orders_confirm
    get 'orders/complete' => 'orders#complete', as: :orders_complete
    resources :orders, only: [:index, :new, :create, :show]
  end



  get "admin" => "admin/homes#top"

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    post '/admin/sign_in', to: 'admins/sessions#create', as: :admin_session
    delete '/admin/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  namespace :admin do
    resources :homes, only: []
    resources :items, except: [:destroy]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :personal]
    get 'orders/:id/personal' => 'orders#personal', as: :orders_personal


  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name,         presence: true, length: {maximum: 10 }
  validates :first_name,        presence: true, length: {maximum: 10 }
  validates	:last_name_kana,    presence: true, length: {maximum: 10 }
  validates :first_name_kana,   presence: true, length: {maximum: 10 }
  validates :telephone_number, 	presence: true, length: {maximum: 12, minimum: 10 }
  validates :postal_code,       presence: true, length: {maximum: 7 }
  validates :address, 		      presence: true, length: {maximum: 255 }
  validates :email, 			      presence: true, length: {maximum: 255 }
  validates :is_active,        inclusion: [true, false]



  has_many :cart_items
  has_many :orders
  has_many :order_details


  def active_for_authentication?
    super && is_active
  end

  def inactive_message
    is_active ? super : :mail_not_replied
  end
end

app/models/item.rb
class Item < ApplicationRecord
  
  
  
  
  has_many :cart_items
  has_many :order_details


  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
  
  enum payment: {クレジットカード: 0, 銀行振込: 1}
  
  has_many :order_details
  
  belongs_to :customer
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  extend ActiveModel::Translation
  include ActiveModel::AttributeMethods
  include ActiveModel::Validations
  attr_accessor :collection  
  
  
  belongs_to :order
  belongs_to :item
  
  

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @items = Item.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])

  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all

  end

  def show
    @order = Order.find(params[:id])
  end

  def personal
    @orders = Order.where(customer_id: params[:id])
    render :index
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


 

 

  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [
  	  :last_name,
  	  :first_name,
  	  :last_name_kana,
  	  :first_name_kana,
  	  :telephone_number,
  	  :postal_code,
  	  :address,
  	  :email
  	  ])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.page(params[:page]).per(4)
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tax_include(price)
    return (price*1.1).floor
  end

	def sub_total_price(cart)
		return cart
	end

	def total_price(carts)
	   total_price =0
	   carts.each do |cart|
	     total_price += tax_include(cart.item.price)*cart.amount
	     end
	     return total_price
	end
	
	def total_price_detail(order_details)
	   total_price =0
	   order_details.each do |order_detail|
	     total_price += order_detail.purchase_price*order_detail.amount
	     end
	     return total_price
	end
	
	def total_amount(order_details)
		total_amount =0
		order_details.each do |order_detail|
			total_amount += order_detail.amount
		end
		return total_amount
	end




end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <div class="texts">
        <ul class="links">
            <li><%= link_to "トップページ", root_path, style:"color:#008080;" %></li>
            <li> | </li>
            <li><%= link_to "このサイトについて", about_path, style:"color:#008080;" %></li>
        </ul>
        <div class="copyrights">
            <p>©︎ All rights reserved by One-Short-Lib</p>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>

  <nav class="navbar">


      <%= link_to root_path, class:"navbar-left" do %>
        <span class="logo"><i class="fas fa-store"></i>ながのCAKE</span>
      <% end %>


    <% if admin_signed_in? %>
     <style>
      header{height:110px;}
    </style>
<!-- 管理者様ヘッダー -->
        <ul class = "nav navbar-nav navbar-right">

          <li><%= link_to admin_items_path  do %>
            <i class="fas fa-birthday-cake"> 商品一覧</i>
            <%end%>
          </li>
          <li><%= link_to admin_customers_path  do %>
            <i class="fas fa-users"> 会員一覧</i>
            <%end%>
          </li>
          <li><%= link_to admin_orders_path  do %>
            <i class="fas fa-list-alt"> 注文履歴一覧</i>
            <%end%>
          </li>
          <li><%= link_to destroy_admin_session_path, method: :delete  do %>
            <i class="fas fa-sign-out-alt"> ログアウト</i>
            <%end%>
          </li>
         </ul>

         <!-- 会員用ヘッダー -->
         <% elsif customer_signed_in? %>
         <ul class = "nav navbar-nav navbar-right">
          <li><%= link_to members_path  do %>
            <i class="fas fa-user-shield"> マイページ</i>
            <%end%>
          </li>
          <li><%= link_to items_path  do %>
            <i class="fas fa-birthday-cake"> 商品一覧</i>
            <%end%>
          </li>
          <li><%= link_to cart_items_path  do %>
            <i class="fas fa-shopping-cart"> カート</i>
            <%end%>
          </li>
          <li><%= link_to destroy_customer_session_path, method: :delete  do %>
            <i class="fas fa-sign-out-alt"> ログアウト</i>
            <%end%>
          </li>
         </ul>

         <!-- 未登録顧客用ヘッダー -->
         <% else %>
         <ul class = "nav navbar-nav navbar-right">
          <li><%= link_to about_path  do %>
            <i class="fas fa-birthday-cake"> About</i>
            <%end%>
          </li>
          <li><%= link_to items_path  do %>
            <i class="fas fa-users"> 商品一覧</i>
            <%end%>
          </li>
          <li><%= link_to new_customer_registration_path do %>
            <i class="fas fa-plus-circle"> 新規登録</i>
            <%end%>
          </li>
          <li><%= link_to new_customer_session_path do %>
            <i class="fas fa-sign-out-alt"> ログイン</i>
            <%end%>
          </li>
         </ul>

    　<%end%>

    </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "/layouts/header" %>
    
    
      <%= yield %>
    
    <%= render "/layouts/footer" %>
  </body>
</html>